# Use docker-based build environment (instead of openvz)
sudo: false

language: java
jdk:
  - oraclejdk8
env:
  global:
    - MAVEN_OPTS="-XX:MaxPermSize=512m -Xmx4g"

cache:
  directories:
      - '$HOME/.m2/repository'

install: /bin/true
script:
  - mvn -B clean install && cd hapi-fhir-cobertura && mvn -B -DTRAVIS_JOB_ID=$TRAVIS_JOB_ID -P COBERTURA clean cobertura:cobertura coveralls:report 
#  - mvn -B clean install -Dcobertura.skip=true && mvn -B -DTRAVIS_JOB_ID=$TRAVIS_JOB_ID -P COBERTURA clean cobertura:cobertura coveralls:report 


